apiVersion: v1
stringData:
  credentials: |-
    [default]
    sts_regional_endpoints = regional
    role_arn = arn:aws:iam::800216399102:role/my-role-dev-aws-creds
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
kind: Secret
metadata:
  name: aws-creds
  namespace: dev
type: Opaque